/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_brugere;

/**
 *
 * @author quent
 */
public class Cadenas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadenas.class.getName());

    /**
     * Creates new form Cadenas
     */
    public Cadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_chiffre_4 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Trouvez le bon code en - de 5 tentatives!");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, 336, -1));

        up_chiffre_1.setText("UP");
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, -1, -1));

        up_chiffre_2.setText("UP");
        up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 42, -1, -1));

        up_chiffre_3.setText("UP");
        up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 42, -1, -1));

        up_chiffre_4.setText("UP");
        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 42, -1, -1));

        texte_chiffre_1.setText("0");
        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 86, 37, -1));

        texte_chiffre_2.setText("0");
        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 86, 37, -1));

        texte_chiffre_3.setText("0");
        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 86, 37, -1));

        texte_chiffre_4.setText("0");
        getContentPane().add(texte_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 86, 37, -1));

        down_chiffre_1.setText("DOWN");
        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 129, -1, -1));

        down_chiffre_2.setText("DOWN");
        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 129, -1, -1));

        down_chiffre_3.setText("DOWN");
        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 129, -1, -1));

        down_chiffre_4.setText("DOWN");
        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 129, -1, -1));

        bouton_tester.setText("Tester");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 83, -1, -1));

        texte_lbl_nb_chiffres_exacts.setText("Nb de bon chiffres :");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        texte_nb_chiffres_exacts.setText("0");
        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 20, -1));

        texte_lbl_nb_chiffres_haut.setText("Nb chiffres trop haut");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        texte_nb_chiffres_haut.setText("0");
        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 10, -1));

        texte_lbl_nb_chiffres_bas.setText("Nb chiffres trop bas :");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        texte_nb_chiffres_bas.setText("0");
        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 20, -1));

        texte_score.setText("jLabel1");
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_chiffre_4;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
