/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_brugere;

/**
 *
 * @author quent
 */
public class page_accueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(page_accueil.class.getName());

    /**
     * Creates new form page_accueil
     */
    public page_accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bienvenue = new javax.swing.JLabel();
        texte_diff = new javax.swing.JLabel();
        diff_10 = new javax.swing.JButton();
        diff_7 = new javax.swing.JButton();
        diff_5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvenue.setText("BIENVENUE");
        getContentPane().add(Bienvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 6, 79, -1));

        texte_diff.setText("Veuillez choisir un niveau de difficulté");
        getContentPane().add(texte_diff, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 59, 210, -1));

        diff_10.setText("Facile (10vie)");
        diff_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff_10ActionPerformed(evt);
            }
        });
        getContentPane().add(diff_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 169, -1, -1));

        diff_7.setText("Moyen (7vie)");
        diff_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff_7ActionPerformed(evt);
            }
        });
        getContentPane().add(diff_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 169, -1, -1));

        diff_5.setText("Difficile (5vie)");
        diff_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff_5ActionPerformed(evt);
            }
        });
        getContentPane().add(diff_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diff_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff_10ActionPerformed
    Cadenas fenetreJeu = new Cadenas();
    fenetreJeu.initialiserJeu(10); 
    this.dispose();
    }//GEN-LAST:event_diff_10ActionPerformed

    private void diff_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff_7ActionPerformed
    Cadenas fenetreJeu = new Cadenas();
    fenetreJeu.initialiserJeu(7); 
    this.dispose();
    }//GEN-LAST:event_diff_7ActionPerformed

    private void diff_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff_5ActionPerformed
    Cadenas fenetreJeu = new Cadenas();
    fenetreJeu.initialiserJeu(5); 
    this.dispose();
    }//GEN-LAST:event_diff_5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new page_accueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenue;
    private javax.swing.JButton diff_10;
    private javax.swing.JButton diff_5;
    private javax.swing.JButton diff_7;
    private javax.swing.JLabel texte_diff;
    // End of variables declaration//GEN-END:variables
}
